- name: Replace API keys with secrets
      run: |
        echo "Replacing placeholders with secrets..."
        # More precise replacements - only replace variable assignments
        sed -i "s/= 'GOOGLE_VISION_API_KEY_PLACEHOLDER'/= '${{ secrets.GOOGLE_VISION_API_KEY }}'/g" index.html
        sed -i "s|= 'SUPABASE_URL_PLACEHOLDER'|= '${{ secrets.SUPABASE_URL }}'|g" index.html  
        sed -i "s/= 'SUPABASE_ANON_KEY_PLACEHOLDER'/= '${{ secrets.SUPABASE_ANON_KEY }}'/g" index.html
        echo "Replacement complete!"
        echo "Verifying replacements..."
        if grep -q "= '.*PLACEHOLDER" index.html; then
          echo "❌ Some placeholders remain!"
          grep "= '.*PLACEHOLDER" index.html
        else
          echo "✅ All assignment placeholders replaced successfully!"
        fi
